# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['date']},
        ),
    ]
