# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0002_auto_20180211_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'get_latest_by': 'created_at', 'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='top',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Street, City'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='indoor.Gym', verbose_name='Gym'),
        ),
    ]
