# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0003_auto_20180211_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='route_type',
            field=models.CharField(choices=[('B', 'Boulder'), ('R', 'Rope')], default='R', max_length=100),
        ),
    ]
