# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0004_auto_20180211_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'get_latest_by': 'created_at', 'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='gym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
