# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0006_auto_20180217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='ascent_style',
            field=models.CharField(choices=[('OS', 'OS'), ('FL', 'Flash'), ('RP', 'RP'), ('PP', 'PP'), ('AF', 'AF'), ('TR', 'TR')], max_length=100, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='top',
            name='route_type',
            field=models.CharField(choices=[('B', 'Boulder'), ('R', 'Rope')], default='R', max_length=100, verbose_name='Type'),
        ),
    ]
