# Generated by Django 2.0.2 on 2018-02-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0009_auto_20180222_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
