# Generated by Django 2.0.2 on 2018-02-25 14:55

import django.core.validators
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('indoor', '0010_top_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Input needs to consist of street and city names divided by a comma (,) and a space', regex='.+,\\s.+')], verbose_name='Street, City'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='52.2479423,20.953566', max_length=63),
        ),
    ]
