# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20180205_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascent',
            name='ascent_style',
            field=models.CharField(choices=[('OS', 'OS'), ('FL', 'Flash'), ('RP', 'RP'), ('PP', 'PP'), ('AF', 'AF'), ('TR', 'TR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='protection',
            field=models.CharField(choices=[(('EQ',), 'Equipped'), (('TR',), 'TRAD'), ('MX', 'Mixed')], default=('EQ',), max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('SP', 'Single Pitch'), ('MP', 'Multi Pitch'), ('BLD', 'Boulder')], default='SP', max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='scale',
            field=models.CharField(choices=[('YDS', 'YDS'), ('FR', 'French'), ('UIAA', 'UIAA'), ('POL', 'Polish'), ('V', 'Verm')], default='FR', max_length=100),
        ),
    ]
