# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20180205_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='protection',
            field=models.CharField(choices=[('EQ', 'Equipped'), ('TR', 'TRAD'), ('MX', 'Mixed')], default='EQ', max_length=100),
        ),
    ]
