# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20180205_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('SP', 'Single-Pitch'), ('MP', 'Multi-Pitch'), ('BLD', 'Boulder')], default='SP', max_length=50),
        ),
    ]
