# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_ascent_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascent',
            name='rating',
            field=models.IntegerField(choices=[(0, 'No rating'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0),
        ),
    ]
