# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20180205_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ascent',
            options={'get_latest_by': ['created_at'], 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'get_latest_by': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ascent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ascent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
