# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20180209_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'get_latest_by': 'created_at', 'ordering': ['country', 'name']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'get_latest_by': 'created_at', 'ordering': ['location', 'name']},
        ),
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.Place'),
        ),
    ]
