# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20180209_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'get_latest_by': 'created_at', 'ordering': ['country', 'city', 'name']},
        ),
    ]
