# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_auto_20180209_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
    ]
