# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0019_auto_20180212_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
