# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0020_auto_20180212_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
