# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0021_auto_20180214_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='grade_bld_fr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='grade_bld_v',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='grade_fr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='grade_pol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='grade_uiaa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='grade_yds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='scale',
            field=models.CharField(choices=[('YDS', 'YDS'), ('FR', 'French'), ('UIAA', 'UIAA'), ('POL', 'Polish'), ('V', 'Vermin')], default='FR', max_length=50),
        ),
    ]
