# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0025_auto_20180217_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade_fr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade_pol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade_uiaa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade_yds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
