# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0026_auto_20180217_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='grade_bld_v',
        ),
        migrations.RemoveField(
            model_name='route',
            name='grade_pol',
        ),
        migrations.RemoveField(
            model_name='route',
            name='grade_uiaa',
        ),
        migrations.RemoveField(
            model_name='route',
            name='grade_yds',
        ),
    ]
