# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0027_auto_20180217_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('region', models.CharField(max_length=100, verbose_name='Region, Country')),
                ('country', models.CharField(max_length=100)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'get_latest_by': 'created_at', 'ordering': ['sector', 'name']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='location',
        ),
        migrations.AlterField(
            model_name='ascent',
            name='ascent_style',
            field=models.CharField(choices=[('OS', 'OS'), ('FL', 'Flash'), ('RP', 'RP'), ('PP', 'PP'), ('AF', 'AF'), ('TR', 'TR')], default='OS', max_length=20, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('SP', 'Single-Pitch'), ('MP', 'Multi-Pitch'), ('BLD', 'Boulder')], default='SP', max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='route',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.Sector'),
            preserve_default=False,
        ),
    ]
