# Generated by Django 2.0.2 on 2018-02-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0028_auto_20180221_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'get_latest_by': 'created_at', 'ordering': ['country', 'region', 'name']},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='grade_bld_fr',
            new_name='grade_converted',
        ),
        migrations.RemoveField(
            model_name='route',
            name='grade_fr',
        ),
    ]
