# Generated by Django 2.0.2 on 2018-02-23 22:08

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0029_auto_20180222_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='37.8535178,-119.8319915', max_length=63),
        ),
    ]
