# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180207_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
