# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180209_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='wojt@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
