# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180209_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars'),
        ),
    ]
