# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180209_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/user_placeholder.png', null=True, upload_to='accounts/avatars/'),
        ),
    ]
