# Generated by Django 2.0.2 on 2018-02-22 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180218_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='user-placeholder-circle_o5pzxf.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
